### ISSUE TITLE
LineageTree of C.elegans not showing for Treeroot=P0

### ISSUE THREAD

**Issue by so-phi** [qinzhu/VisCello#3]
I get the following error, when I select Tree root = P0 (other categories do not matter):
`An error has occurred. Check your logs or contact the app author for clarification.`

Generally, I would like to see+download the complete lineage tree of c.elegans and understand that P0 is the overarching ancestor of all cells

**Comment by qinzhu** [comment]
This might be due to some package not up to date. It is now functional. Sorry about the inconvenience.
