### ISSUE TITLE
Load multiple datasets

### ISSUE THREAD

**Issue by Gregory94** [qinzhu/VisCello#6]
Hello,

Would it be possible to load multiple datasets (i.e. multiple eset.rds and clist.rds) simultaneously in the same app? For example, that one can select at 'Choose Sample' different expression sets and corresponding dimension reductions.

Thanks in advance!

Best,
Gregory

**Comment by qinzhu** [comment]
Hi Gregory,
Unfortunately the feature you described is not supported at this moment. 
But right now you can accomplish the same thing by building all cells into a single eset.rds object, then for each dimension reduction for the cell subsets, use the cello@idx = match(cell_subset_barcode, colnames(eset)) to let Viscello know which set of cells in the global eset.rds the current cello object corresponds to. Then after you create different cello objects for different cell subsets, build them into a list and save as clist.rds. names(clist) should be the desired name for each cell subset, like "My cell subset 1", "Cell subset2" etc. Then you can find these subsets in the "Choose sample" dropdown.

Best,
Qin

**Comment by Gregory94** [comment]
Hi Qin,

Thanks you for your reply! I afraid I'm not sure how to build all cells into a single eset object. I am using seurat objects from which I gather all information using the approach you describe in the readme. Each seurat oject has different number of genes and cells, I don't know if this would be a problem?

Best,
Gregory

**Comment by qinzhu** [comment]
Hi sorry for delayed response - haven't actively checked repo due to job change. Currently VisCello can only handle a unified dataset at one time. Meaning you either have to combine them by not filtering genes (Seurat filters genes with zero expression) and merge them, or visualize them separately.
