### ISSUE TITLE
Can VisCello create or embed heatmap ?

### ISSUE THREAD

**Issue by DengEr-1993** [qinzhu/VisCello#8]
Hi, sir

I recently studied the https://cello.shinyapps.io/kidneycellexplorer/.

And the author of the article said VisCello was used in their website. But I was confused by VisCello.

In the second part, if the heatmap  is related to VisCello ??

Could you help me ?

**Comment by qinzhu** [comment]
Hi the tool borrows modules/functions from VisCello but the heatmap is independent design.
