### ISSUE TITLE
Extracting high-dimensional data for cross-validation

### ISSUE THREAD

**Issue by martinskrodzki** [qinzhu/VisCello#9]
How can I extract the c.elegans data that has been used in the computation of the UMAP embedding? After running the cello(...) command, I don't see any objects of the expected size (~86,000) in the R.Data.

**Comment by qinzhu** [comment]
Hi sorry for the delayed response. You can see an eset object in the session once you run cello(...) and close the window. Alternatively, you can readRDS("inst/app/data/eset.rds") to get the same ExpressionSet object containing all data.
